

image: maven:3.6.3

pipelines:
  default:
    - parallel:
        - step:
            size: 2x
            name: Testleri KoÅŸuyoruzuu
            caches:
              - maven
            script:
              - mvn clean install
            after-script:
              - BUILD_STATUS="â˜•ï¸ TESTLER TAMAM ðŸ¥° ðŸ¤Ÿ"
              - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then BUILD_STATUS=" ðŸ‘Ž TESTLER HATALI BRO ðŸ’©" ; fi
              - echo "branch durumu -> ${BUILD_STATUS}"
